### ISSUE TITLE
Extension has been removed from Mozilla Addons

### ISSUE THREAD

**Issue by QazCetelic** [mcclure/NFTBlocker#8]
The _Twitter Block Chain_ add-on page seems to have been removed.

![image](https://user-images.githubusercontent.com/51381523/150532172-453125e3-9230-4c5f-bb03-5fc44ea5ef7a.png)

**Comment by gaeulbyul** [comment]
Hello, The link in the README points to Twitter Block Chain, not NFTBlocker. (note that NFTBlocker is not published to addons store yet)

See also: https://github.com/mcclure/NFTBlocker/issues/4#issuecomment-989034496
